/* Online Click & Collect — FAQ page. Keep policy language clear, honest, and easy to scan. */
import { ChevronDown, MessageCircle, ArrowLeft } from "lucide-react";

const questions = [
  ["How do I place an order?", "Choose your product, note its product code, and send it to us on WhatsApp or Messenger. We will confirm availability, the final total, delivery charges, and the expected delivery time before dispatch."],
  ["Is Cash on Delivery available?", "Yes, Cash on Delivery is available where our delivery service operates. Please keep the confirmed amount ready when the parcel arrives."],
  ["Where do you deliver?", "We are based in Karachi. Karachi delivery is available; wider Pakistan delivery depends on the product and courier coverage. Please confirm your city and delivery charges before ordering."],
  ["How long does delivery take?", "Delivery time depends on your location and the product. Our team confirms the expected timeline on WhatsApp before dispatch. We do not promise a fixed number of days unless it is confirmed for your order."],
  ["Can I return or exchange a product?", "Return or exchange eligibility depends on the product and its condition. The item should be unused, undamaged, and in its original packaging. Contact us as soon as possible with your order number and an unboxing video so our team can guide you."],
  ["What if my parcel arrives damaged?", "Please record an unboxing video from the sealed parcel to the opened product and contact us immediately with your order number. This helps us review the issue fairly."],
  ["How can I check my order status?", "Send your order number on WhatsApp or Messenger. We will share the latest status, including confirmation, packing, dispatch, or delivery."],
];

export default function FAQ() {
  return <div className="min-h-screen bg-[#fffaf3] text-[#231f20]"><header className="border-b border-[#eadfd3] bg-[#fffaf3]/95"><div className="container flex h-20 items-center justify-between"><a href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#6b5e56]"><ArrowLeft size={16} /> Back to store</a><a href="/" className="font-serif text-xl">Online <span className="text-[#c95b63]">Click & Collect</span></a><a href="https://wa.me/923001234567" className="inline-flex items-center gap-2 rounded-full bg-[#c95b63] px-4 py-2 text-xs font-bold text-white" target="_blank" rel="noreferrer"><MessageCircle size={15} /> WhatsApp</a></div></header><main className="container max-w-4xl py-20 lg:py-28"><p className="eyebrow">Helpful answers</p><h1 className="mt-3 max-w-2xl font-serif text-[clamp(3rem,7vw,6rem)] leading-[.9] tracking-[-.06em]">Good to know<br /><em className="font-normal text-[#c95b63]">before you order.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#796b62]">Clear information makes online shopping feel better. If your question is not here, send us a message and our team will help.</p><div className="mt-12 grid gap-3">{questions.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-[#dfc9b8] bg-[#f5ede3]/55 px-5 open:bg-[#fffdf8]"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-5 font-bold marker:hidden"><span>{question}</span><ChevronDown size={18} className="shrink-0 text-[#c95b63] transition-transform group-open:rotate-180" /></summary><p className="max-w-3xl border-t border-[#eadfd3] pb-5 pt-4 text-sm leading-7 text-[#796b62]">{answer}</p></details>)}</div></main><footer className="border-t border-[#eadfd3] py-8"><div className="container flex flex-col justify-between gap-3 text-xs text-[#927c6d] sm:flex-row"><span>© 2026 Online Click & Collect</span><a href="/contact" className="font-bold text-[#c95b63]">Contact us →</a></div></footer></div>;
}
