/* Online Click & Collect — Bazaar Editorial admin product manager. */
import { useEffect, useState } from "react";
import { Check, Edit3, Loader2, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { fastApi, type Product } from "@/lib/api";

type FormState = { id: string; name: string; category: string; price: string; stock: string; image_url: string; description: string; is_active: boolean };
const blankForm: FormState = { id: "", name: "", category: "Kitchen", price: "", stock: "", image_url: "", description: "", is_active: true };
const priceLabel = (value: number) => `Rs. ${value.toLocaleString("en-PK")}`;

export default function ProductManager({ products, onSaved }: { products: Product[]; onSaved: (product: Product, editingId: string | null) => void }) {
  const [open, setOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<FormState>(blankForm);
  const [saving, setSaving] = useState(false);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState("");
  useEffect(() => () => { if (imagePreview) URL.revokeObjectURL(imagePreview); }, [imagePreview]);
  const openAdd = () => { setEditingId(null); setForm(blankForm); setImageFile(null); setImagePreview(""); setOpen(true); };
  const openEdit = (product: Product) => { setEditingId(product.id); setForm({ id: product.id, name: product.name, category: product.category, price: String(product.price), stock: String(product.stock), image_url: product.image_url || "", description: product.description || "", is_active: product.is_active }); setImageFile(null); setImagePreview(""); setOpen(true); };
  const update = (key: keyof FormState, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const price = Number(form.price); const stock = Number(form.stock);
    if (!form.name.trim() || !form.category.trim() || !Number.isFinite(price) || price < 0 || !Number.isInteger(stock) || stock < 0) { toast.error("Enter a valid name, category, price, and whole-number stock."); return; }
    setSaving(true);
    try {
      const payload = { name: form.name.trim(), category: form.category.trim(), price, stock, image_url: form.image_url.trim() || undefined, description: form.description.trim() || undefined, is_active: form.is_active };
      let saved = editingId ? await fastApi.updateProduct(editingId, payload) : await fastApi.createProduct({ name: payload.name, category: payload.category, price: payload.price, stock: payload.stock, image_url: payload.image_url, description: payload.description });
      if (imageFile) { const uploaded = await fastApi.uploadProductImage(saved.id, imageFile); saved = await fastApi.updateProduct(saved.id, { image_url: uploaded.url }); }
      onSaved(saved, editingId); setOpen(false); setImageFile(null); setImagePreview(""); toast.success(editingId ? "Product updated" : "Product created");
    } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save product"); } finally { setSaving(false); }
  };
  return <section id="product-manager" className="mt-10 rounded-2xl border border-[#dfc9b8] bg-[#fffaf3] p-5 lg:p-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">Catalog management</p><h2 className="mt-1 font-serif text-2xl">Products</h2><p className="mt-2 text-sm text-[#796b62]">Create new finds or edit pricing, stock, imagery, and visibility without touching code.</p></div><button type="button" onClick={openAdd} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#c95b63] px-4 py-2.5 text-xs font-bold text-white"><Plus size={15} /> Add product</button></div>
    {open && <form onSubmit={save} className="mt-6 rounded-2xl border border-[#eadfd3] bg-[#f5ede3] p-5" aria-label={editingId ? "Edit product" : "Add product"}><div className="flex items-center justify-between"><div><p className="eyebrow">{editingId ? "Edit listing" : "New listing"}</p><h3 className="mt-1 font-serif text-xl">{editingId ? `Update ${form.id}` : "Add a product"}</h3></div><button type="button" onClick={() => setOpen(false)} className="icon-button" aria-label="Close product form"><X size={17} /></button></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-[#6b5e56]">Product name<input required value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="e.g. Bamboo Spice Rack Set" className="admin-field" /></label><label className="text-xs font-bold text-[#6b5e56]">Category<input required list="product-categories" value={form.category} onChange={(event) => update("category", event.target.value)} placeholder="Kitchen" className="admin-field" /><datalist id="product-categories"><option value="Kitchen" /><option value="Beauty & Care" /><option value="Home Living" /><option value="Gadgets" /><option value="Gifting" /><option value="Decor" /><option value="Everyday" /><option value="Deals" /></datalist></label><label className="text-xs font-bold text-[#6b5e56]">Price (Rs.)<input required min="0" step="1" type="number" value={form.price} onChange={(event) => update("price", event.target.value)} placeholder="2190" className="admin-field" /></label><label className="text-xs font-bold text-[#6b5e56]">Stock quantity<input required min="0" step="1" type="number" value={form.stock} onChange={(event) => update("stock", event.target.value)} placeholder="25" className="admin-field" /></label><label className="text-xs font-bold text-[#6b5e56] sm:col-span-2">Main product image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={saving} onChange={(event) => { const file = event.target.files?.[0]; event.currentTarget.value = ""; if (!file) return; if (!["image/png", "image/jpeg", "image/webp"].includes(file.type)) { toast.error("Please choose a PNG, JPG, or WEBP image."); return; } if (file.size > 5 * 1024 * 1024) { toast.error("Image must be smaller than 5 MB."); return; } if (imagePreview) URL.revokeObjectURL(imagePreview); setImageFile(file); setImagePreview(URL.createObjectURL(file)); }} className="admin-field file:mr-3 file:rounded-full file:border-0 file:bg-[#f7dfd8] file:px-3 file:py-2 file:text-xs file:font-bold file:text-[#a8434d]" /><span className="mt-1 block text-[11px] font-normal text-[#927c6d]">Upload PNG, JPG, or WEBP up to 5 MB. A selected file becomes the main image after saving.</span>{(imagePreview || form.image_url) && <img src={imagePreview || form.image_url} alt="Selected product preview" className="mt-3 h-24 w-24 rounded-xl border border-[#dfc9b8] object-cover" />}</label><label className="text-xs font-bold text-[#6b5e56] sm:col-span-2">Description<textarea value={form.description} onChange={(event) => update("description", event.target.value)} placeholder="A short, useful description for the product page" className="admin-field min-h-24" /></label><label className="inline-flex items-center gap-2 text-xs font-bold text-[#6b5e56] sm:col-span-2"><input type="checkbox" checked={form.is_active} onChange={(event) => update("is_active", event.target.checked)} className="h-4 w-4 accent-[#c95b63]" /> Visible in storefront</label></div>
      <div className="mt-5 flex flex-wrap gap-2"><button disabled={saving} aria-busy={saving} className="primary-button" type="submit">{saving ? <><Loader2 size={16} className="animate-spin" /> Saving...</> : <><Check size={16} /> {editingId ? "Save changes" : "Create product"}</>}</button><button type="button" onClick={() => setOpen(false)} className="text-link">Cancel</button></div></form>}
    <div className="mt-6 grid gap-3">{products.length ? products.map((product) => <article key={product.id} className="flex flex-col gap-4 rounded-xl border border-[#eadfd3] bg-[#f5ede3] p-4 sm:flex-row sm:items-center"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-[#eadfd3]">{product.image_url ? <img src={product.image_url} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-xs text-[#a77966]">No image</div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{product.name}</p><span className="rounded-full bg-[#fffaf3] px-2 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#a77966]">{product.category}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-[.12em] ${product.is_active ? "bg-[#e7f5eb] text-[#2f8060]" : "bg-[#f7dfd8] text-[#a8434d]"}`}>{product.is_active ? "Live" : "Hidden"}</span></div><p className="mt-1 text-xs text-[#796b62]">{product.id} · {priceLabel(product.price)} · {product.stock} in stock</p></div><button type="button" onClick={() => openEdit(product)} className="inline-flex items-center justify-center gap-2 rounded-full border border-[#d8c7b8] px-4 py-2 text-xs font-bold text-[#6b5e56] hover:bg-[#fffaf3]"><Edit3 size={14} /> Edit</button></article>) : <div className="rounded-xl border border-dashed border-[#d8c7b8] p-8 text-center text-sm text-[#796b62]">No live products loaded. Connect FastAPI to create your first product.</div>}</div>
  </section>;
}
